title: MONICA EU Project
logo: /assets/img/monica.png
description: This is the tutorial related to MONICA EU Project artefacts. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
collections_dir: contents
collections:
  sections:
    output: true