title: MONICA EU Project
logo: /assets/img/monica.png
description: This work is supported by the European Commission through the MONICA H2020 PROJECT under grant agreement No 732350. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
collections_dir: contents

collections:
  sections:
    output: true

github:
  is_project_page: true
  is_user_page: true


markdown: kramdown
